--錯字 p.10  PEPORT_COACH_NO_SEQ;  -> REPORT_COACH_NO_SEQ;
--P.30 PASSWARD -> PASSWORD  。  P.86 PASSWARD -> PASSWORD
--P.97 COACH_INTROTUCTION->COACH_INTRODUCTION   。  p.188  PEPORT_COACH_NO->REPORT_COACH_NO
--刪TABLE
ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-mm-dd hh24:mi:ss';
DROP TABLE SYSTEM_NEWS ;
    DROP SEQUENCE SYSTEM_NEWS_NO_SEQ; 

DROP TABLE REPORT_COACH;
    DROP SEQUENCE REPORT_COACH_NO_SEQ; 

DROP TABLE TOP_UP_RECORD;
    DROP SEQUENCE TOP_UP_RECORD_NO_SEQ; 

DROP TABLE COACH;
    DROP SEQUENCE COACH_NO_SEQ; 

DROP TABLE MEMBER;
    DROP SEQUENCE MEMBER_NO_SEQ; 
    
     

----------------------------會員--------------------------------------------
CREATE TABLE MEMBER (
    MEMBER_NO VARCHAR2(4) PRIMARY KEY NOT NULL,
    MEMBER_NAME VARCHAR2(10) NOT NULL,
    MEMBER_SEX VARCHAR2(5) NOT NULL,
    MEMBER_CELLPHONE VARCHAR2(10),
    MEMBER_ACCOUNT VARCHAR2(40) NOT NULL UNIQUE,
    MEMBER_PASSWORD VARCHAR2(40) NOT NULL,
    MEMBER_ADDRESS VARCHAR2(100),
    MEMBER_PHOTO BLOB,
    MEMBER_POINTS NUMBER(10) CHECK (MEMBER_POINTS >= 0) NOT NULL,
    MEMBER_HEIGHT NUMBER(5),
    MEMBER_WEIGHT NUMBER(5),
    MEMBER_REVIEW NUMBER(1) CHECK (MEMBER_REVIEW >= 0) NOT NULL,
    MEMBER_AUTH NUMBER(1) CHECK (MEMBER_AUTH >= 0) NOT NULL,
    MEMBER_BODYFAT NUMBER(5,2),
    MEMBER_CARD VARCHAR2(19)
    );
    --自動編號
    CREATE SEQUENCE MEMBER_NO_SEQ 
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOCYCLE
        NOCACHE;
    --INSERT
    INSERT INTO MEMBER (MEMBER_NO                            ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , 'TEDDY'    ,'男'       ,'0977590543',   'TEDDY8525@gmail.com'     ,'123ABC'         , '彰化員林'    , NULL        , 0            ,NULL          ,   NULL      , 0            ,   0        , NULL        ,'5896-7878-0123-6480');

    INSERT INTO MEMBER (MEMBER_NO                           ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0') , 'SARA'    ,'女'        ,'0912345543'    ,'SARASARA@yahoo.com'     ,'1234567'        , '台北天母'   , NULL        , 0            ,169          ,   45         , 1            ,   1        , NULL          ,'8763-1256-9876-2312');

    INSERT INTO MEMBER (MEMBER_NO                            ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , 'DAVID'    ,'男'        ,'0977490213'   ,'54DAVID@gmail.com'      ,'8476KID'       , '新北板橋'    , NULL        , 0            ,175           ,   60         , 2            ,   0        , 16.34       ,'5101-7420-3265-5205');

    INSERT INTO MEMBER (MEMBER_NO                            ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , 'PETER'    ,'男'        ,'0917590043'    ,'PETER2020@outlook.com' ,'ASDFQWER'       , '台中烏日'    , NULL        , 1000          ,180          ,   NULL      , 0            ,   1        , NULL         ,'7958-0314-4165-7785');
    
     INSERT INTO MEMBER (MEMBER_NO                           ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , 'GOODGOOD' ,'女'        ,'0987590123'    ,'GOODGOOD123@outlook.com' ,'123ABC'        , '台中北區'    , NULL        , 0          ,NULL          ,   40         , 1            ,   0        , NULL           ,'0301-7571-9876-3087'  );
    
     INSERT INTO MEMBER (MEMBER_NO                           ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , '小明'     ,'男'        ,'0983651890'    ,'MINGMING123@Ggmail.com'   ,'123ABC'         , '桃園平鎮'    , NULL        , 0          ,180          ,   NULL      , 2            ,   1        , NULL           ,'0234-8919-7683-1205');

     INSERT INTO MEMBER (MEMBER_NO                           ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , '結衣'    ,'女'        ,'0917174520'    , 'JAYYEE520@ntu.edu.com'   ,'NOTYOURWIFI'   , '桃園三井'    , NULL        , 100000       ,161          ,45            , 2            ,1           , NULL          ,'7967-3521-7986-3248');
    
     INSERT INTO MEMBER (MEMBER_NO                           ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , '小吳'     ,'男'        ,'0937827163'     ,'SEADFOODLOL@outlook.com','INTERFACE'     , '南投龍井'    , NULL        , 0            ,180          ,   84         , 1            ,   1        , 5.2         ,'0012-3579-3456-1579');

     INSERT INTO MEMBER (MEMBER_NO                           ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , '阿美'      ,'男'       ,'0929591043'    ,'MAYMAY1542@yahoo,com'   ,'7775401'        , '高雄'       , NULL        , 500          ,180          ,   NULL      , 2            ,   0        , NULL          ,'2046-6676-8975-0314');

     INSERT INTO MEMBER (MEMBER_NO                           ,MEMBER_NAME ,MEMBER_SEX ,MEMBER_CELLPHONE ,MEMBER_ACCOUNT           ,MEMBER_PASSWORD ,MEMBER_ADDRESS ,MEMBER_PHOTO ,MEMBER_POINTS ,MEMBER_HEIGHT ,MEMBER_WEIGHT,MEMBER_REVIEW ,MEMBER_AUTH ,MEMBER_BODYFAT  ,MEMBER_CARD)
        VALUES('M'||LPAD(TO_CHAR(MEMBER_NO_SEQ.NEXTVAL),3,'0')  , 'SCOTTER'  ,'男'        ,'099847043'    ,'SCOTTERLAI@gmail.com'    ,'123ABC'        , '花蓮'        , NULL        ,0            ,NULL          ,   NULL      , 0            ,   1        , NULL          ,'8967-1230-2020-7890');
    --INSERT END
    
    ----------------------------教練--------------------------------------------
CREATE TABLE COACH (
    COACH_NO VARCHAR2(4) PRIMARY KEY NOT NULL,
    COACH_NAME VARCHAR2(10) NOT NULL,
    COACH_SEX VARCHAR2(5) NOT NULL,
    COACH_CELLPHONE VARCHAR2(10),
    COACH_ACCOUNT VARCHAR2(40) NOT NULL UNIQUE,
    COACH_PASSWORD VARCHAR2(40) NOT NULL,
    COACH_ADDRESS VARCHAR2(100),
    COACH_PHOTO BLOB,
    COACH_TOTAL_EVALUATION NUMBER(10),
    COACH_TOTAL_PEOPLE_EVALUATION NUMBER(10),
    COACH_REVIEW NUMBER(1) NOT NULL,
    COACH_AUTH NUMBER(1) NOT NULL,
    COACH_AVERAGE_EVALUATION  NUMBER(5,1),
    COACH_LICENSE BLOB,
    COACH_INCOME NUMBER(10) NOT NULL,
    COACH_INTRODUCTION VARCHAR2(4000),
    COACH_BANK_ACCOUNT VARCHAR2(14)
);
    --自動編號
CREATE SEQUENCE COACH_NO_SEQ
       INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOCYCLE
        NOCACHE;
    
    --INSERT
    INSERT INTO COACH (COACH_NO                              ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'YEE'      ,'男'      ,'0934985714'     ,'YEEDADIA@pchome.com'   ,'PCHOMEGOOD'     ,'新竹'         , NULL        , 11                  , 777                          ,0            ,0          , 1.1                    , NULL         ,0             ,'我是一位健身教練'  ,'241-004-178461');

     INSERT INTO COACH (COACH_NO                              ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'SNOWWHITE' ,'女'      ,'0918052671'    ,'SNOWISWHY@yahoo.com'   ,'SOWHITE'        ,'苗栗'         , NULL        , 666                  , 9528                         ,1            ,0          , 5.0                    , NULL         ,0             ,'我是瑜珈教練'      ,'785-110-178561');

     INSERT INTO COACH (COACH_NO                               ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'AMY'       ,'女'      ,'0953298756'     ,'AMYNETA@gmail.com'     ,'AMYTIERD'      ,'美國紐約'      , NULL        , 11                  , 42                          ,4            ,1          , 3.1                    , NULL           ,8000          ,'你好,歡迎來上課'      ,'123-456-123456' );

     INSERT INTO COACH (COACH_NO                              ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'ADOM'      ,'男'      ,'0912786547'     ,'IAMADOM@pchome.com'   ,'ADOM123GOOD'     ,'台中'         , NULL        , 11                  , 2                          ,4            ,2          , 4.4                    , NULL           ,0              ,'WORK IT OUT'     ,'897-654-321012');

     INSERT INTO COACH (COACH_NO                              ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'ALEX'      ,'男'      ,'0949876623'    ,'ERMOALEX@yahoo.com'  ,'PCHOMEALEX'    ,'雲林'         , NULL        , 11                  , 0                            ,4            ,0          , 3.2                    , NULL         ,0               , 'HELLO ~~'          ,'862-004-178543');

     INSERT INTO COACH (COACH_NO                              ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'JOME'      ,'男'      ,'0998563214'     ,'JOMERAY@outlook.com'   ,'JOMEOUTLOOK'    ,'桃園中壢'     , NULL        , 11                  , 8861                          ,4            ,2          , 1.9                    , NULL         ,1000         ,'TIME IS MONEY'      ,'396-302-798613');

     INSERT INTO COACH (COACH_NO                               ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'ESON'      ,'男'      ,'086409014'     ,'9876ESON@pchome.com'    ,'ESONSINGIT'    ,'彰化'         , NULL        , 11                  , 777                          ,0            ,0          , 1.8                    , NULL         ,1000           ,'PLAY WITH ME'     ,'023-874-137953');

     INSERT INTO COACH (COACH_NO                               ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'LOERN'      ,'男'      ,'0994123123'     ,'LOERNLOERN@yahoo.com'  ,'PCHOMEGOOD'     ,'美國舊金山'    , NULL        , 11                  , 98751                          ,1            ,0          , 4.1                    , NULL         ,0          , 'WORK HARD'         ,'849-102-302168');

     INSERT INTO COACH (COACH_NO                             ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'OLIVER'      ,'女'      ,'0934636714'     ,'OLIVERVER@gmail.com' ,'MAILOLIVER'     ,'新竹'         , NULL        , 11                  , 231                          ,2            ,0          , 5.0                    , NULL         ,8500          , 'LIFE WORK'       ,'877-101-396369');

     INSERT INTO COACH (COACH_NO                            ,COACH_NAME ,COACH_SEX ,COACH_CELLPHONE ,   COACH_ACCOUNT         ,COACH_PASSWORD  ,COACH_ADDRESS ,COACH_PHOTO ,COACH_TOTAL_EVALUATION ,COACH_TOTAL_PEOPLE_EVALUATION ,COACH_REVIEW ,COACH_AUTH ,COACH_AVERAGE_EVALUATION ,COACH_LICENSE ,COACH_INCOME  ,COACH_INTRODUCTION ,COACH_BANK_ACCOUNT)
        VALUES( 'C'||LPAD(TO_CHAR(COACH_NO_SEQ.NEXTVAL),3,'0'),'TIM'      ,'男'      ,'0914985714'     ,'TIMTOM@pchome.com'      ,'TIMISGOOD'     ,'基隆'         , NULL        , 11                  , 99                          ,1            ,0          , 2.8                    , NULL         ,0               ,'TAKE SOME PAY'  ,'474-130-879567');

---------------------------------------TOP_UP_RECORD-------------------

CREATE TABLE TOP_UP_RECORD(
    TOP_UP_RECORD_NO VARCHAR2(4) PRIMARY KEY NOT NULL,
    MEMBER_NO VARCHAR2(4) NOT NULL,
        CONSTRAINT FK_TOP_UP_RECORD_MEMBER
        FOREIGN KEY (MEMBER_NO)REFERENCES MEMBER(MEMBER_NO) ,
    RECORD_TIME TIMESTAMP NOT NULL,
    MONEY_RECORD NUMBER(10) NOT NULL
        
);
  CREATE SEQUENCE   TOP_UP_RECORD_NO_SEQ 
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOCYCLE
        NOCACHE; 
--INSERT
INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                            ,MEMBER_NO   ,RECORD_TIME              ,MONEY_RECORD)
VALUES( 'T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M001'       ,SYSDATE                 , 100 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                          ,MEMBER_NO  ,RECORD_TIME ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')       ,'M010'     ,SYSDATE     , 100 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                           ,MEMBER_NO  ,RECORD_TIME  ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M008'     ,SYSDATE      , 800 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                          ,MEMBER_NO  ,RECORD_TIME    ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')       ,'M006'     ,SYSDATE        , 400 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                           ,MEMBER_NO  ,RECORD_TIME ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M003'     ,SYSDATE     , 3000 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                           ,MEMBER_NO  ,RECORD_TIME     ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M002'     ,SYSDATE         , 900 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                           ,MEMBER_NO  ,RECORD_TIME       ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M007'     ,SYSDATE           , 1300 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                           ,MEMBER_NO  ,RECORD_TIME   ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M009'     ,SYSDATE       , 600000 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                           ,MEMBER_NO  ,RECORD_TIME   ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M005'     ,SYSDATE       , 10500 );

INSERT INTO TOP_UP_RECORD(TOP_UP_RECORD_NO                           ,MEMBER_NO  ,RECORD_TIME   ,MONEY_RECORD)
VALUES('T'||LPAD(TO_CHAR(TOP_UP_RECORD_NO_SEQ.NEXTVAL),3,'0')        ,'M004'     ,SYSDATE       , 10500 );

--INSERT END
---------------------------------------REPORT_COACH-------------------
CREATE TABLE REPORT_COACH(
    REPORT_COACH_NO VARCHAR2(5) PRIMARY KEY NOT NULL,
    COACH_NO VARCHAR2(4)  NOT NULL,
        CONSTRAINT FK_REPORT_COACH_COACH 
        FOREIGN KEY (COACH_NO) REFERENCES COACH(COACH_NO) ,
    MEMBER_NO VARCHAR2(4) NOT NULL,
        CONSTRAINT FK_REPORT_COACH_MEMBER
        FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    REPORT_COACH_CONTENT VARCHAR2 (500) NOT NULL ,
    REPORT_COACH_TIME TIMESTAMP NOT NULL,
    REPORT_COACH_STATUS NUMBER(1) NOT NULL
);
    CREATE SEQUENCE REPORT_COACH_NO_SEQ 
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOCYCLE
        NOCACHE;
        
       
--INSERT
INSERT INTO REPORT_COACH(REPORT_COACH_NO                              ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME   ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C001'    ,'M010'     ,'上的很爛'          ,SYSDATE             ,0);
    
INSERT INTO REPORT_COACH(REPORT_COACH_NO                             ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME     ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C008'    ,'M001'     ,'趕快審核'           ,SYSDATE              ,2);

INSERT INTO REPORT_COACH(REPORT_COACH_NO                                ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME  ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C006'    ,'M009'     ,'你好'              ,SYSDATE           ,0);

INSERT INTO REPORT_COACH(REPORT_COACH_NO                               ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME     ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C008'    ,'M005'     ,'我要檢舉'           ,SYSDATE              ,1);

INSERT INTO REPORT_COACH(REPORT_COACH_NO                               ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME   ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C009'    ,'M003'     ,'太貴'             ,SYSDATE              ,2);

INSERT INTO REPORT_COACH(REPORT_COACH_NO                               ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME   ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C001'    ,'M004'     ,'教練遲到'           ,SYSDATE            ,1);
    
INSERT INTO REPORT_COACH(REPORT_COACH_NO                              ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME   ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C006'    ,'M007'     ,'不會教..'           ,SYSDATE            ,2);
    
INSERT INTO REPORT_COACH(REPORT_COACH_NO                              ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME    ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C007'    ,'M008'     ,'WORSE'            ,SYSDATE              ,1);
    
INSERT INTO REPORT_COACH(REPORT_COACH_NO                               ,COACH_NO ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME  ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C009'    ,'M002'     ,'NOTGOODGOOD'           ,SYSDATE       ,0);
    
INSERT INTO REPORT_COACH(REPORT_COACH_NO                                ,COACH_NO  ,MEMBER_NO ,REPORT_COACH_CONTENT ,REPORT_COACH_TIME     ,REPORT_COACH_STATUS )
    VALUES ('RC'||LPAD(TO_CHAR(REPORT_COACH_NO_SEQ.NEXTVAL),3,'0')     ,'C004'    ,'M008'     ,'時數太少'           ,SYSDATE               ,2);
    
--INSERT END
---------------------------------------SYSTEM_NEWS -------------------
CREATE TABLE SYSTEM_NEWS (
    SYSTEM_NEWS_NO VARCHAR2(4) NOT NULL PRIMARY KEY ,
    MEMBER_NO VARCHAR2(4),
        CONSTRAINT FK_SYSTEM_NEWS_MEMBER
        FOREIGN KEY (MEMBER_NO)REFERENCES MEMBER(MEMBER_NO),
    COACH_NO VARCHAR2(4),
        CONSTRAINT FK_SYSTEM_NEWS_COACH
        FOREIGN KEY (COACH_NO)REFERENCES COACH(COACH_NO),
    SYSTEM_CONTENT VARCHAR2(500) NOT NULL,  
    SYSTEM_TIME TIMESTAMP NOT NULL
);
CREATE SEQUENCE SYSTEM_NEWS_NO_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
--INSERT
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                           , MEMBER_NO , COACH_NO    ,SYSTEM_CONTENT          ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M010'    , 'C010'      , '2020/1/19要上瑜珈課喔'  ,SYSDATE );
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                            , MEMBER_NO , COACH_NO    ,SYSTEM_CONTENT          ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M004'    , 'C010'      , '2020/1/22要上健身課喔' ,SYSDATE );
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                           , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT             ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M003'    , NULL     , '您已訂購健身課程'          ,SYSDATE);
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                          , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT             ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M001'    ,'C001'    , '歡迎使用本網站'             ,SYSDATE);
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                           , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT             ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , NULL       ,'C005'    , '免責聲明'               ,SYSDATE );
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                          , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT             ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M009'    , NULL      , '訂購商品已付款'            ,SYSDATE);
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                         , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT             ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M006'    , NULL     , '貨物已送達指定地點'        ,SYSDATE);
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                         , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT             ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , NULL       , 'C007'  , '現在有預約教練功能可以使用' ,SYSDATE );
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                           , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT               ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M007'    , 'C006'   , '直播功能已經上線,歡迎觀賞使用' ,SYSDATE);
    
    INSERT INTO SYSTEM_NEWS(SYSTEM_NEWS_NO                           , MEMBER_NO , COACH_NO ,SYSTEM_CONTENT             ,SYSTEM_TIME)
    VALUES('S'||LPAD(TO_CHAR(SYSTEM_NEWS_NO_SEQ.NEXTVAL),3,'0')     , 'M001'    , NULL      , '2020/1/20要上108的預約喔' ,SYSDATE);
--INSERT_END
------------------------------------COMMIT----------------------------------
COMMIT;